// 行程判斷一律以明確 ISO offset 儲存，避免台灣 UTC+8 / 越南 UTC+7 混用造成一小時誤差。
// ?testTime=2026-09-14T15:42 未帶 offset 時，視為峴港 Asia/Ho_Chi_Minh（UTC+7）時間。
const DANANG_TZ='Asia/Ho_Chi_Minh',TAIPEI_TZ='Asia/Taipei';
const destinations={
 hotel:{name:'Peninsula Hotel Danang',lat:16.0957,lng:108.245,mapQuery:'Peninsula Hotel Danang'},
 moc:{name:'Mộc quán Seafood Đà Nẵng',lat:16.0666,lng:108.24,mapQuery:'Moc quan Seafood Da Nang 26 To Hien Thanh'},
 brilliant:{name:'BRILLIANT SEAFOOD',lat:16.0714,lng:108.2447,mapQuery:'Brilliant Seafood 178 Ho Nghinh Da Nang'},
 dad:{name:'Da Nang International Terminal T2',lat:16.0439,lng:108.1994,mapQuery:'Da Nang International Terminal T2'},
 tpe:{name:'桃園國際機場第二航廈',mapQuery:'Taiwan Taoyuan International Airport Terminal 2'}
};
const places=[
 {...destinations.hotel,type:'住宿',days:['2026-09-14','2026-09-15','2026-09-16','2026-09-17','2026-09-18'],map:'https://www.google.com/maps/search/?api=1&query=Peninsula+Hotel+Danang'},
 {...destinations.moc,type:'9/14 晚餐',days:['2026-09-14'],map:'https://www.google.com/maps/search/?api=1&query=Moc+quan+Seafood+Da+Nang+26+To+Hien+Thanh'},
 {...destinations.brilliant,type:'9/16 公司晚宴',days:['2026-09-16'],map:'https://www.google.com/maps/search/?api=1&query=Brilliant+Seafood+178+Ho+Nghinh+Da+Nang'},
 {...destinations.dad,type:'9/18 回程機場',days:['2026-09-18'],map:'https://www.google.com/maps/search/?api=1&query=Da+Nang+International+Terminal+T2'}
];
// 結構化既有固定行程與頁面已明確寫出的自由時段；沒有可靠地點時不猜座標。
const itinerary=[
 {id:'d1-transfer',day:'2026-09-14',start:'2026-09-14T06:30:00+08:00',end:'2026-09-14T07:00:00+08:00',title:'送機接送出發',type:'transfer',important:true,zone:TAIPEI_TZ},
 {id:'d1-tpe',day:'2026-09-14',start:'2026-09-14T07:00:00+08:00',end:'2026-09-14T09:45:00+08:00',title:'桃園機場第二航廈集合',detail:'長榮航空 18 號櫃檯',type:'meeting',important:true,destination:destinations.tpe,zone:TAIPEI_TZ},
 {id:'d1-flight',day:'2026-09-14',start:'2026-09-14T09:45:00+08:00',end:'2026-09-14T11:35:00+07:00',title:'BR383 前往峴港',type:'flight',important:true,zone:TAIPEI_TZ},
 {id:'d1-arrive',day:'2026-09-14',start:'2026-09-14T11:35:00+07:00',end:'2026-09-14T13:30:00+07:00',title:'抵達峴港／前往飯店',type:'transfer',destination:destinations.hotel,zone:DANANG_TZ},
 {id:'d1-free1',day:'2026-09-14',start:'2026-09-14T13:30:00+07:00',end:'2026-09-14T17:00:00+07:00',title:'自由活動',detail:'飯店附近、美溪沙灘、咖啡、按摩',type:'free',destination:destinations.hotel,zone:DANANG_TZ},
 {id:'d1-dinner',day:'2026-09-14',start:'2026-09-14T18:00:00+07:00',end:'2026-09-14T20:00:00+07:00',title:'PPA 聚餐：Mộc quán Seafood',type:'meal',important:true,destination:destinations.moc,zone:DANANG_TZ},
 {id:'d1-free2',day:'2026-09-14',start:'2026-09-14T20:00:00+07:00',end:'2026-09-14T23:59:59+07:00',title:'自由活動',type:'free',zone:DANANG_TZ},
 {id:'d2-free',day:'2026-09-15',start:'2026-09-15T00:00:00+07:00',end:'2026-09-15T23:59:59+07:00',title:'完整自由日',detail:'公司無固定集合時間或指定地點',type:'free',destination:destinations.hotel,zone:DANANG_TZ},
 {id:'d3-free',day:'2026-09-16',start:'2026-09-16T00:00:00+07:00',end:'2026-09-16T16:30:00+07:00',title:'自由活動',detail:'下午建議回飯店整理',type:'free',destination:destinations.hotel,zone:DANANG_TZ},
 {id:'d3-meet',day:'2026-09-16',start:'2026-09-16T17:50:00+07:00',end:'2026-09-16T18:00:00+07:00',title:'BRILLIANT SEAFOOD 集合',type:'meeting',important:true,destination:destinations.brilliant,zone:DANANG_TZ},
 {id:'d3-dinner',day:'2026-09-16',start:'2026-09-16T18:00:00+07:00',end:'2026-09-16T21:00:00+07:00',title:'全公司聚餐',type:'meal',important:true,destination:destinations.brilliant,zone:DANANG_TZ},
 {id:'d3-free2',day:'2026-09-16',start:'2026-09-16T21:00:00+07:00',end:'2026-09-16T23:59:59+07:00',title:'自由活動',type:'free',zone:DANANG_TZ},
 {id:'d4-free',day:'2026-09-17',start:'2026-09-17T00:00:00+07:00',end:'2026-09-17T23:59:59+07:00',title:'完整自由日',detail:'公司無固定集合時間或指定地點',type:'free',destination:destinations.hotel,zone:DANANG_TZ},
 {id:'d5-free',day:'2026-09-18',start:'2026-09-18T00:00:00+07:00',end:'2026-09-18T10:30:00+07:00',title:'早餐／整理行李',type:'free',destination:destinations.hotel,zone:DANANG_TZ},
 {id:'d5-airport',day:'2026-09-18',start:'2026-09-18T10:30:00+07:00',end:'2026-09-18T12:55:00+07:00',title:'峴港機場 T2 集合',detail:'自行前往',type:'meeting',important:true,destination:destinations.dad,zone:DANANG_TZ},
 {id:'d5-flight',day:'2026-09-18',start:'2026-09-18T12:55:00+07:00',end:'2026-09-18T16:45:00+08:00',title:'BR384 返回桃園',type:'flight',important:true,zone:DANANG_TZ},
 {id:'d5-arrive',day:'2026-09-18',start:'2026-09-18T16:45:00+08:00',end:'2026-09-18T18:00:00+08:00',title:'抵達桃園／接機接送',type:'transfer',important:true,destination:destinations.tpe,zone:TAIPEI_TZ}
].map(i=>({...i,startDate:new Date(i.start),endDate:new Date(i.end)}));
const dayLabels={'2026-09-14':'Day 1','2026-09-15':'Day 2','2026-09-16':'Day 3','2026-09-17':'Day 4','2026-09-18':'Day 5'};
const tripStart=new Date('2026-09-14T06:30:00+08:00'),tripEnd=new Date('2026-09-18T18:00:00+08:00');
function pad2(n){return String(n).padStart(2,'0')}
function getTestTime(){const raw=new URLSearchParams(location.search).get('testTime');if(!raw)return null;const hasZone=/(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw),normalized=hasZone?raw:`${raw}${raw.length===16?':00':''}+07:00`,d=new Date(normalized);return Number.isNaN(d.getTime())?null:d}
const testTime=getTestTime();function getNow(){return testTime?new Date(testTime.getTime()):new Date()}
const formatters={taiwan:new Intl.DateTimeFormat('zh-TW',{timeZone:TAIPEI_TZ,hour:'2-digit',minute:'2-digit',hour12:false}),vietnam:new Intl.DateTimeFormat('zh-TW',{timeZone:DANANG_TZ,hour:'2-digit',minute:'2-digit',hour12:false})};
function dateKeyInDanang(date){const p=new Intl.DateTimeFormat('en-CA',{timeZone:DANANG_TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
function formatHM(date,zone=DANANG_TZ){return new Intl.DateTimeFormat('zh-TW',{timeZone:zone,hour:'2-digit',minute:'2-digit',hour12:false}).format(date)}
function formatRange(i){return `${formatHM(i.startDate,i.zone||DANANG_TZ)}–${formatHM(i.endDate,i.zone||DANANG_TZ)}`}
function formatRemaining(ms){if(ms<=0)return'現在';const mins=Math.max(0,Math.ceil(ms/60000)),h=Math.floor(mins/60),m=mins%60;if(h&&m)return`${h} 小時 ${m} 分`;if(h)return`${h} 小時`;return`${m} 分鐘`}
function getDayItems(day){return itinerary.filter(i=>i.day===day).sort((a,b)=>a.startDate-b.startDate)}
function computeTravelState(now){const day=dateKeyInDanang(now),todayItems=getDayItems(day),active=todayItems.find(i=>now>=i.startDate&&now<i.endDate)||null,future=todayItems.filter(i=>i.startDate>now),next=future[0]||null,nextImportant=future.find(i=>i.important)||null,inTrip=day>='2026-09-14'&&day<='2026-09-18';if(!inTrip){const n=itinerary.filter(i=>i.startDate>now).sort((a,b)=>a.startDate-b.startDate)[0]||null;return{day,todayItems:[],active:null,next:n,nextImportant:n?.important?n:null,status:now<tripStart?'before-trip':'after-trip'}}if(todayItems.length&&now<todayItems[0].startDate)return{day,todayItems,active:null,next:todayItems[0],nextImportant:todayItems.find(i=>i.important)||null,status:'day-not-started'};if(!active&&!next)return{day,todayItems,active:null,next:null,nextImportant:null,status:'day-finished'};if(!active&&next)return{day,todayItems,active:null,next,nextImportant,status:'gap'};return{day,todayItems,active,next,nextImportant,status:'active'}}
function googleDirectionsUrl(dest){if(!dest)return'';const value=Number.isFinite(dest.lat)&&Number.isFinite(dest.lng)?`${dest.lat},${dest.lng}`:dest.mapQuery||dest.name;return`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(value)}&travelmode=driving`}
let toastTimer;function showToast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2600)}
async function copyDestination(dest){if(!dest)return false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(dest.name);return true}}catch(e){}return false}
function openGrab(dest){/* Grab 官方活動頁仍使用 grab://open?screenType=BOOKING。未找到一般網站可公開、穩定預填目的地的 consumer deep-link 參數，所以不硬塞未公開參數。 */copyDestination(dest).then(copied=>{if(copied)showToast('已複製目的地，Grab 開啟後可直接貼上');const ua=navigator.userAgent||'',fallback=encodeURIComponent('https://www.grab.com/vn/');if(/Android/i.test(ua))location.href=`intent://open?screenType=BOOKING#Intent;scheme=grab;package=com.grabtaxi.passenger;S.browser_fallback_url=${fallback};end`;else{location.href='grab://open?screenType=BOOKING';setTimeout(()=>{if(document.visibilityState==='visible')window.open('https://www.grab.com/vn/','_blank','noopener')},1200)}})}
function haversineKm(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),x=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
let currentLiveDestination=null;function requestDistance(){const out=document.getElementById('liveDistance');if(!currentLiveDestination||!Number.isFinite(currentLiveDestination.lat)||!Number.isFinite(currentLiveDestination.lng))return;if(!navigator.geolocation){out.textContent='此瀏覽器不支援定位';return}out.textContent='正在取得目前位置…';navigator.geolocation.getCurrentPosition(p=>{const km=haversineKm(p.coords.latitude,p.coords.longitude,currentLiveDestination.lat,currentLiveDestination.lng);out.textContent=`📍 距離目的地約 ${km<1?(km*1000).toFixed(0)+' m':km.toFixed(1)+' km'}（直線距離）`},e=>{out.textContent=e.code===1?'未取得定位權限；不影響其他功能':'目前無法取得位置；可直接使用 Google Maps 導航'},{enableHighAccuracy:false,timeout:8000,maximumAge:120000})}
function updateLiveMode(){const now=getNow(),state=computeTravelState(now),box=document.getElementById('liveMode'),dayNo=dayLabels[state.day];document.getElementById('liveDayTitle').textContent=dayNo?`🇻🇳 峴港 ${dayNo}`:'🇻🇳 峴港旅遊現場';document.getElementById('liveClock').textContent=`越南 ${formatHM(now,DANANG_TZ)}`;const test=document.getElementById('testModeLabel');if(testTime){test.classList.add('show');test.textContent=`測試時間：${state.day} ${formatHM(now,DANANG_TZ)}（越南）`}else test.classList.remove('show');let nt='',tm='';if(state.active){nt=state.active.title;tm=formatRange(state.active)+(state.active.detail?`｜${state.active.detail}`:'')}else if(state.status==='before-trip'){nt='旅程尚未開始';tm='目前顯示下一個已知行程'}else if(state.status==='after-trip'){nt='旅程已結束';tm='2026/9/14－9/18'}else if(state.status==='gap'){nt='自由／移動時間';tm='目前沒有固定行程'}else if(state.status==='day-finished'){nt='今天行程已結束';tm='可以自由安排'}else nt='今天尚未開始';document.getElementById('liveNowTitle').textContent=nt;document.getElementById('liveNowTime').textContent=tm;const next=state.next,label=document.getElementById('liveNextLabel'),title=document.getElementById('liveNextTitle'),time=document.getElementById('liveNextTime'),cd=document.getElementById('liveCountdown'),dest=document.getElementById('liveDestination'),maps=document.getElementById('liveMapsBtn'),grab=document.getElementById('liveGrabBtn'),loc=document.getElementById('liveLocationBtn'),note=document.getElementById('liveGrabNote');document.getElementById('liveDistance').textContent='';currentLiveDestination=next?.destination||null;box.classList.remove('live-warn','live-urgent');if(next){const ms=next.startDate-now,mins=ms/60000;if(next.important&&mins<30){box.classList.add('live-urgent');label.textContent='🔴 即將開始'}else if(next.important&&mins<=60){box.classList.add('live-warn');label.textContent='🟡 接下來'}else label.textContent='⚠️ 下一個';title.textContent=next.title;time.textContent=`${formatHM(next.startDate,next.zone||DANANG_TZ)}${next.detail?`｜${next.detail}`:''}`;cd.textContent=`距離下一個行程：${formatRemaining(ms)}`;dest.textContent=next.destination?`地點：${next.destination.name}`:'';const has=!!next.destination;maps.hidden=!has;grab.hidden=!has;loc.hidden=!(has&&Number.isFinite(next.destination.lat)&&Number.isFinite(next.destination.lng));if(has){maps.href=googleDirectionsUrl(next.destination);grab.onclick=()=>openGrab(next.destination)}note.textContent=has?'Grab 會嘗試開啟叫車頁；目的地名稱會先複製，若無法自動帶入可直接貼上。':''}else{label.textContent='下一個';title.textContent=state.status==='after-trip'?'沒有後續行程':'今天沒有下一個固定行程';time.textContent='';cd.textContent='';dest.textContent='';maps.hidden=true;grab.hidden=true;loc.hidden=true;note.textContent=''}renderDayTimelines(now)}
document.getElementById('liveLocationBtn').addEventListener('click',requestDistance);
function renderDayTimelines(now){document.querySelectorAll('.trip-day').forEach(card=>{const items=getDayItems(card.dataset.tabDay),list=card.querySelector('[data-timeline]');if(!list)return;list.innerHTML='';const nextImportant=items.find(i=>i.startDate>now&&i.important);items.forEach(item=>{const li=document.createElement('li');if(now>=item.endDate)li.className='done';else if(now>=item.startDate&&now<item.endDate)li.className='now';else li.className='upcoming';if(nextImportant&&item.id===nextImportant.id)li.classList.add('next-important');const t=document.createElement('span');t.className='tl-time';t.textContent=formatHM(item.startDate,item.zone||DANANG_TZ);const n=document.createElement('span');n.textContent=item.title;li.append(t,n);if(item.destination){const d=document.createElement('span');d.className='tl-dest';d.textContent=item.destination.name;li.append(d)}list.append(li)})})}
let map=null,mapMarkers=null;function initMap(){if(map)return;map=L.map('map',{scrollWheelZoom:false,zoomControl:true});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);mapMarkers=L.layerGroup().addTo(map);renderMapForTab(currentTab||'all')}
function applyMapViewport(v){if(!map||mapCollapse.hidden)return;map.invalidateSize({pan:false});requestAnimationFrame(()=>{map.invalidateSize({pan:false});if(v.length===1)map.setView([v[0].lat,v[0].lng],15,{animate:false});else if(v.length>1)map.fitBounds(L.latLngBounds(v.map(p=>[p.lat,p.lng])),{padding:[30,30],animate:false})})}
function renderMapForTab(tab){const l=document.getElementById('mapScopeLabel');if(l)l.textContent=tab==='all'?'全部行程':tab.slice(5).replace('-','/');if(!map||!mapMarkers)return;mapMarkers.clearLayers();const v=tab==='all'?places:places.filter(p=>p.days.includes(tab));v.forEach(p=>L.marker([p.lat,p.lng]).addTo(mapMarkers).bindPopup(`<strong>${p.name}</strong><br>${p.type}<br><br><a href="${p.map}" target="_blank" rel="noopener">Google Maps 開啟</a>`));applyMapViewport(v)}
const mapToggle=document.getElementById('mapToggle'),mapCollapse=document.getElementById('mapCollapse');mapToggle.addEventListener('click',()=>{const open=mapCollapse.hidden;mapCollapse.hidden=!open;mapToggle.setAttribute('aria-expanded',open?'true':'false');if(open){initMap();renderMapForTab(currentTab||'all');setTimeout(()=>renderMapForTab(currentTab||'all'),120);setTimeout(()=>renderMapForTab(currentTab||'all'),320)}});window.addEventListener('resize',()=>{if(map&&!mapCollapse.hidden)renderMapForTab(currentTab||'all')});
function updateLocalTimes(){const n=getNow();document.getElementById('taiwanTime').textContent=formatters.taiwan.format(n);document.getElementById('vietnamTime').textContent=formatters.vietnam.format(n)}
function updateCountdown(){const n=getNow(),el=document.getElementById('countdown'),sub=document.getElementById('countdownSub'),diff=tripStart-n;if(diff>0){const s=Math.floor(diff/1000),d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60),sec=s%60;el.innerHTML=`<span class="num">${d}</span> 天 <span class="num">${pad2(h)}</span> 時 <span class="num">${pad2(m)}</span> 分 <span class="num">${pad2(sec)}</span> 秒`;sub.textContent='送機接送：2026/9/14 06:30（台灣時間）'}else if(n<=tripEnd){el.textContent='旅程進行中 ✈️';sub.textContent='最上方「旅行現場」會依目前時間自動顯示現在與下一個行程'}else{el.textContent='旅程已結束';sub.textContent='2026/9/14－9/18 越南峴港員工旅遊'}}
function updateCurrentTrip(){const now=getNow(),day=dateKeyInDanang(now);document.querySelectorAll('.trip-day').forEach(c=>c.classList.toggle('current-day',c.dataset.tabDay===day));const steps=[...document.querySelectorAll('.trip-step')];steps.forEach(s=>s.classList.remove('current-step','next-step'));const active=steps.find(s=>s.dataset.start&&s.dataset.end&&now>=new Date(s.dataset.start)&&now<new Date(s.dataset.end));if(active){active.classList.add('current-step');return}const next=steps.filter(s=>s.dataset.start&&new Date(s.dataset.start)>now).sort((a,b)=>new Date(a.dataset.start)-new Date(b.dataset.start))[0];if(next)next.classList.add('next-step')}
let userSelectedTab=false,currentTab=null;function autoTabForNow(){const n=getNow();if(n<tripStart||n>=new Date('2026-09-19T00:00:00+07:00'))return'all';const d=dateKeyInDanang(n);return dayLabels[d]?d:'all'}
function selectDayTab(tab,fromUser=false){currentTab=tab;if(fromUser)userSelectedTab=true;document.querySelectorAll('.day-tab').forEach(b=>{const a=b.dataset.tab===tab;b.classList.toggle('active',a);b.setAttribute('aria-selected',a?'true':'false');if(a)b.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})});document.querySelectorAll('.trip-day').forEach(c=>c.classList.toggle('tab-hidden',tab!=='all'&&c.dataset.tabDay!==tab));document.querySelectorAll('.all-only').forEach(x=>x.classList.toggle('tab-hidden',tab!=='all'));renderMapForTab(tab)}
document.querySelectorAll('.day-tab').forEach(b=>b.addEventListener('click',()=>selectDayTab(b.dataset.tab,true)));selectDayTab(autoTabForNow());updateLocalTimes();updateCountdown();updateCurrentTrip();updateLiveMode();setInterval(()=>{updateLocalTimes();updateCurrentTrip();updateLiveMode();if(!userSelectedTab){const t=autoTabForNow();if(t!==currentTab)selectDayTab(t)}},30000);setInterval(updateCountdown,testTime?30000:1000);